export const DEFAULT_SLIPPAGE = '0.5'
export const DEFAULT_TOKENS_LIMIT = '10000000'
export const DEFAULT_REQUEST_RETRY_INTERVAL_MS = 3000 // 3 seconds
export const DEFAULT_RETRY_COUNT = 3
export const DEFAULT_INDENTATION = 2
export const DEFAULT_CONFIRMATIONS = 3
