export const rpcsMap: Record<string, string[]> = {
	'42161': [
		'https://arbitrum-one.publicnode.com',
		'https://rpc.ankr.com/arbitrum',
		'https://arb1.arbitrum.io/rpc',
		'https://1rpc.io/arb',
		'https://arbitrum.drpc.org',
		'https://arbitrum.blockpi.network/v1/rpc/public',
	],
	'43114': [
		'https://avalanche.drpc.org',
		'https://endpoints.omniatech.io/v1/avax/mainnet/public',
		'https://1rpc.io/avax/c',
		'https://avalanche-c-chain-rpc.publicnode.com',
		'https://avalanche.drpc.org',
		'https://rpc.ankr.com/avalanche',
		'https://avalanche.public-rpc.com',
	],
	'137': [
		'https://1rpc.io/matic',
		'https://endpoints.omniatech.io/v1/matic/mainnet/public',
		'https://polygon.drpc.org',
		'https://polygon-bor-rpc.publicnode.com',
		'https://rpc.ankr.com/polygon',
		'https://polygon.rpc.subquery.network/public',
		'https://polygon-rpc.com',
	],
	'8453': [
		'https://1rpc.io/base',
		'https://base-rpc.publicnode.com',
		'https://endpoints.omniatech.io/v1/base/mainnet/public',
		'https://base-pokt.nodies.app',
		'https://base.blockpi.network/v1/rpc/public',
		'https://0xrpc.io/base',
		'https://mainnet.base.org',
	],
	'10': [
		'https://1rpc.io/op',
		'https://endpoints.omniatech.io/v1/op/mainnet/public',
		'https://op-pokt.nodies.app',
		'https://optimism-rpc.publicnode.com',
		'https://optimism.drpc.org',
		'https://endpoints.omniatech.io/v1/op/mainnet/public',
		'https://mainnet.optimism.io',
	],
}
