name: Concero.io SDK

on:
    push:
        branches:
            - master

jobs:
    publish-gpr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18.x"
                  registry-url: "https://npm.pkg.github.com/"
            - run: npm install
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
